<img src="mioti.png" style="height: 100px">
<center style="color:#888">Data Science with Python </center>

# DSPy1. NumPy basics. Challenge

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Basic-slicing" data-toc-modified-id="Basic-slicing-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Basic slicing</a></span></li><li><span><a href="#A-bit-more-of-slicing" data-toc-modified-id="A-bit-more-of-slicing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>A bit more of slicing</a></span></li></ul></div>

In [1]:
import numpy as np

## Basic slicing

<img src="slicing.png" style="height: 200px">

Dado el siguiente array 2d:

In [17]:
array2d = np.arange(9).reshape(3,3)
array2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Selecciona cada una de las zonas sombreadas en la imagen superior:

In [22]:
# Upper-right square
upper_right = array2d[[0,1], 1:]
print("Upper-right square:")
print(upper_right)


Upper-right square:
[[1 2]
 [4 5]]


In [23]:
# Last row
last_row = array2d[2, :]
print("Last row:")
print(last_row)

Last row:
[6 7 8]


In [24]:
# First two columns
first_two_columns = array2d[:, :2]
print("First two columns:")
print(first_two_columns)


First two columns:
[[0 1]
 [3 4]
 [6 7]]


In [25]:
# Middle row without last column
middle_row = array2d[1, :-1]
print("Middle row without last column:")
print(middle_row)


Middle row without last column:
[3 4]


## A bit more of slicing

* Crea una matriz tamaño n x m de todo ceros, rodeada de 1s. 

In [7]:
n = 4
m = 9

In [27]:
matrix = np.zeros((n, m))

# Set the border elements to 1
matrix[0, :] = 1  # First row
matrix[-1, :] = 1 # Last row 
matrix[:, 0] = 1  # First column
matrix[:, -1] = 1 # Last column

print("Matrix with border of ones:")
print(matrix)


Matrix with border of ones:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


* Crea una matriz con patrón de tablero de ajedrez. Las casillas negras serán 0, las blancas 1.
<img src="chess.png" style="height: 300px">


In [37]:
# 8x8 chess board pattern
import itertools
n = 8
chess_board = np.zeros((n, n)).astype(int)

# Fill alternating squares with 1s
for i, j in itertools.product(range(n), range(n)):
    if (i + j) % 2 == 0:
        chess_board[int(i), int(j)] = 1

print("Chess board pattern:")
print(chess_board)


Chess board pattern:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
